# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DecorationViewDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  pod ‘MSCrashProtector’
  pod ‘SDWebImage’
  pod ‘Masonry’

  # Pods for DecorationViewDemo

end
